In [1]:
import pandas as pd
df = pd.read_csv('all_seasons.csv')
df

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,...,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,...,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,...,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,...,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,...,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12839,12839,Joel Embiid,PHI,29.0,213.36,127.005760,Kansas,Cameroon,2014,1,...,33.1,10.2,4.2,8.8,0.057,0.243,0.370,0.655,0.233,2022-23
12840,12840,John Butler Jr.,POR,20.0,213.36,86.182480,Florida State,USA,Undrafted,Undrafted,...,2.4,0.9,0.6,-16.1,0.012,0.065,0.102,0.411,0.066,2022-23
12841,12841,John Collins,ATL,25.0,205.74,102.511792,Wake Forest,USA,2017,1,...,13.1,6.5,1.2,-0.2,0.035,0.180,0.168,0.593,0.052,2022-23
12842,12842,Jericho Sims,NYK,24.0,208.28,113.398000,Texas,USA,2021,2,...,3.4,4.7,0.5,-6.7,0.117,0.175,0.074,0.780,0.044,2022-23
12843,12843,JaMychal Green,GSW,33.0,205.74,102.965384,Alabama,USA,Undrafted,Undrafted,...,6.4,3.6,0.9,-8.2,0.087,0.164,0.169,0.650,0.094,2022-23

In [3]:
df.isna().sum()

Unnamed: 0           0
player_name          0
team_abbreviation    0
age                  0
player_height        0
player_weight        0
college              0
country              0
draft_year           0
draft_round          0
draft_number         0
gp                   0
pts                  0
reb                  0
ast                  0
net_rating           0
oreb_pct             0
dreb_pct             0
usg_pct              0
ts_pct               0
ast_pct              0
season               0
dtype: int64

In [6]:
df.groupby(['team_abbreviation'])['player_weight'].mean()

team_abbreviation
ATL    100.572402
BKN     99.636019
BOS    101.238533
CHA     99.567915
CHH    102.037814
CHI     99.491062
CLE    101.337493
DAL     99.783073
DEN     99.721050
DET     99.626774
GSW     99.604873
HOU    100.949284
IND    100.495003
LAC    100.161734
LAL    101.402659
MEM     99.018195
MIA    101.206307
MIL    100.854336
MIN     99.791328
NJN    100.647295
NOH    101.287411
NOK     99.719366
NOP     98.156266
NYK    100.971070
OKC     99.337711
ORL     99.430970
PHI    100.212966
PHX    100.322527
POR     99.473995
SAC    100.456521
SAS     99.690531
SEA    101.195877
TOR     99.827853
UTA    101.697067
VAN     99.651642
WAS    100.302327
Name: player_weight, dtype: float64

In [8]:
df['team_abbreviation'].value_counts()

CLE    450
TOR    446
MIA    443
DAL    443
WAS    442
LAC    442
ATL    439
PHI    438
SAS    434
HOU    433
LAL    429
ORL    428
IND    428
DEN    428
POR    428
MIL    427
GSW    426
NYK    426
BOS    425
CHI    423
DET    419
SAC    418
UTA    417
MIN    417
PHX    415
MEM    370
CHA    305
NJN    257
OKC    255
BKN    200
SEA    182
NOP    175
NOH    143
CHH     89
VAN     72
NOK     32
Name: team_abbreviation, dtype: int64

In [11]:
df.groupby(['age']).describe()

     Unnamed: 0                                                               \
          count         mean          std     min      25%     50%       75%
age
18.0        3.0  1579.666667  2388.052414    72.0   203.00   334.0   2333.50
19.0       76.0  6923.105263  3834.202946   496.0  3781.25  7565.0  10495.00
20.0      318.0  8062.172956  3560.611952   208.0  4843.50  9012.0  11142.00
21.0      534.0  7645.108614  3521.808618    38.0  4708.75  8055.5  10766.25
22.0      817.0  7255.188494  3604.980661     0.0  4466.00  7419.0  10527.00
23.0     1218.0  6677.716749  3663.809478     4.0  3658.75  6701.5   9921.75
24.0     1333.0  6591.855214  3684.071208     8.0  3485.00  6682.0   9734.00
25.0     1195.0  6590.420921  3675.604603    16.0  3504.50  6660.0   9789.00
26.0     1058.0  6431.640832  3686.845662     2.0  3230.50  6613.0   9612.25
27.0     1016.0  6303.158465  3734.585010    27.0  2964.00  6433.0   9481.00
28.0      891.0  6301.769921  3667.491724     1.0  3131.50  6319.0   9488.50
29.0      813.0  6169.398524  3710.698771    12.0  3091.00  6106.0   9361.00
30.0      741.0  6075.214575  3707.101393     3.0  2968.00  5873.0   9231.00
31.0      643.0  5854.979782  3654.987448    11.0  2625.00  5521.0   8917.00
32.0      564.0  5867.503546  3610.686215    23.0  2720.00  5601.5   8817.75
33.0      467.0  5807.710921  3691.994475     5.0  2430.00  5622.0   8836.50
34.0      367.0  5629.760218  3688.020757    18.0  2367.00  5484.0   8578.00
35.0      257.0  5622.735409  3650.333313    59.0  2314.00  5634.0   8436.00
36.0      205.0  5673.273171  3684.724473    24.0  2354.00  5412.0   8912.00
37.0      140.0  5563.528571  3636.402937    43.0  2337.25  4971.0   8540.00
38.0       89.0  5195.573034  3621.365102    97.0  2090.00  4478.0   7956.00
39.0       52.0  4891.211538  3515.306889    48.0  1746.50  3812.0   8118.75
40.0       29.0  5487.655172  3664.206748    64.0  2510.00  4919.0   8948.00
41.0        9.0  6260.555556  4631.430964   759.0  2767.00  4768.0  10233.00
42.0        4.0  7664.500000  4008.911781  3574.0  4596.25  7689.0  10757.25
43.0        4.0  7272.000000  5576.503803   230.0  4134.50  8234.0  11371.50
44.0        1.0  4844.000000          NaN  4844.0  4844.00  4844.0   4844.00

              player_height              ...   ts_pct        ast_pct  \
          max         count        mean  ...      75%    max   count
age                                      ...
18.0   4333.0           3.0  208.280000  ...  0.51900  0.544     3.0
19.0  12773.0          76.0  204.570263  ...  0.54225  1.000    76.0
20.0  12840.0         318.0  201.977925  ...  0.54875  1.025   318.0
21.0  12824.0         534.0  201.568502  ...  0.55300  1.000   534.0
22.0  12830.0         817.0  200.731506  ...  0.55800  1.000   817.0
23.0  12838.0        1218.0  200.381018  ...  0.55900  1.064  1218.0
24.0  12842.0        1333.0  200.243046  ...  0.56100  1.500  1333.0
25.0  12841.0        1195.0  200.403732  ...  0.56400  1.500  1195.0
26.0  12827.0        1058.0  200.387353  ...  0.56900  1.500  1058.0
27.0  12835.0        1016.0  200.383996  ...  0.56600  1.050  1016.0
28.0  12813.0         891.0  200.384242  ...  0.56800  1.064   891.0
29.0  12839.0         813.0  200.444846  ...  0.56800  0.799   813.0
30.0  12750.0         741.0  200.430796  ...  0.56500  1.000   741.0
31.0  12836.0         643.0  200.272877  ...  0.56150  0.738   643.0
32.0  12820.0         564.0  200.002482  ...  0.55925  1.064   564.0
33.0  12843.0         467.0  200.769507  ...  0.56400  0.773   467.0
34.0  12776.0         367.0  200.237820  ...  0.56600  1.064   367.0
35.0  12837.0         257.0  200.679767  ...  0.56300  0.683   257.0
36.0  12828.0         205.0  200.994537  ...  0.56900  0.714   205.0
37.0  12703.0         140.0  200.750714  ...  0.56250  1.000   140.0
38.0  12733.0          89.0  202.457978  ...  0.54100  0.680    89.0
39.0  12606.0          52.0  201.588077  ...  0.54325  1.042    52.0
40.0  11035.0          29.0  202.148966  ...  0.54700  0.626    29.0
41.0  12207.0           9.0  205.457778  ...  0.68900  1.000     9.0
42.0  11706.0           4.0  208.280000  ...  0.57150  0.591     4.0
43.0  12390.0           4.0  208.280000  ...  0.48250  0.514     4.0
44.0   4844.0           1.0  213.360000  ...  0.43200  0.432     1.0


          mean       std    min      25%     50%      75%    max
age
18.0  0.072667  0.062172  0.030  0.03700  0.0440  0.09400  0.144
19.0  0.103395  0.071492  0.000  0.05500  0.0905  0.13750  0.325
20.0  0.120428  0.087745  0.000  0.06025  0.0940  0.16075  0.667
21.0  0.118807  0.087064  0.000  0.05900  0.0920  0.15400  0.454
22.0  0.125361  0.090936  0.000  0.06600  0.0960  0.16200  0.615
23.0  0.121994  0.090873  0.000  0.06300  0.0950  0.16500  0.667
24.0  0.125691  0.093727  0.000  0.06200  0.1010  0.17400  1.000
25.0  0.129918  0.097446  0.000  0.06400  0.1000  0.17250  1.000
26.0  0.132624  0.093651  0.000  0.06600  0.1050  0.17800  0.583
27.0  0.134505  0.093791  0.000  0.06900  0.1080  0.18425  0.505
28.0  0.136622  0.093744  0.000  0.06950  0.1070  0.18600  0.636
29.0  0.133835  0.092046  0.000  0.06900  0.1040  0.18500  0.667
30.0  0.136552  0.092880  0.000  0.06900  0.1070  0.19100  0.500
31.0  0.136428  0.093564  0.000  0.06800  0.1040  0.18900  0.493
32.0  0.143080  0.097516  0.000  0.07100  0.1125  0.20325  0.486
33.0  0.140116  0.092353  0.000  0.06900  0.1180  0.18600  0.468
34.0  0.145752  0.108421  0.000  0.07000  0.1190  0.19950  1.000
35.0  0.143693  0.099256  0.000  0.07400  0.1120  0.19600  0.667
36.0  0.138995  0.094639  0.000  0.07100  0.1110  0.17300  0.483
37.0  0.145700  0.097443  0.000  0.07900  0.1190  0.18450  0.498
38.0  0.133270  0.105150  0.000  0.05900  0.1000  0.18200  0.491
39.0  0.141692  0.106263  0.000  0.06425  0.1015  0.20800  0.452
40.0  0.149207  0.126044  0.007  0.06300  0.1000  0.19300  0.500
41.0  0.082444  0.140552  0.000  0.00000  0.0550  0.06800  0.445
42.0  0.057250  0.037509  0.012  0.03525  0.0600  0.08200  0.097
43.0  0.040750  0.047056  0.000  0.00000  0.0405  0.08125  0.082
44.0  0.034000       NaN  0.034  0.03400  0.0340  0.03400  0.034

[27 rows x 104 columns]

In [12]:
bins = [0, 20, 30, 40, 50, 100]
labels = ['>20','20-30', '30-40', '40-50', '<50']
df['Age Group'] = pd.cut(x=df['age'], bins=bins, labels=labels)
df

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season,Age Group
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,...,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97,20-30
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,...,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97,20-30
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,...,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97,20-30
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,...,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97,20-30
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,...,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97,20-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12839,12839,Joel Embiid,PHI,29.0,213.36,127.005760,Kansas,Cameroon,2014,1,...,10.2,4.2,8.8,0.057,0.243,0.370,0.655,0.233,2022-23,20-30
12840,12840,John Butler Jr.,POR,20.0,213.36,86.182480,Florida State,USA,Undrafted,Undrafted,...,0.9,0.6,-16.1,0.012,0.065,0.102,0.411,0.066,2022-23,>20
12841,12841,John Collins,ATL,25.0,205.74,102.511792,Wake Forest,USA,2017,1,...,6.5,1.2,-0.2,0.035,0.180,0.168,0.593,0.052,2022-23,20-30
12842,12842,Jericho Sims,NYK,24.0,208.28,113.398000,Texas,USA,2021,2,...,4.7,0.5,-6.7,0.117,0.175,0.074,0.780,0.044,2022-23,20-30
12843,12843,JaMychal Green,GSW,33.0,205.74,102.965384,Alabama,USA,Undrafted,Undrafted,...,3.6,0.9,-8.2,0.087,0.164,0.169,0.650,0.094,2022-23,30-40

In [13]:
df.groupby(['Age Group']).describe()

          Unnamed: 0                                                   \
               count         mean          std    min     25%     50%
Age Group
>20            397.0  7795.128463  3668.479971   72.0  4305.0  8782.0
20-30         9616.0  6566.862417  3692.425604    0.0  3423.5  6637.0
30-40         2813.0  5728.829008  3652.978403    5.0  2448.0  5498.0
40-50           18.0  6718.611111  4361.015858  230.0  3470.5  5186.5
<50              0.0          NaN          NaN    NaN     NaN     NaN

                                 age             ...  ts_pct        ast_pct  \
                75%      max   count       mean  ...     75%    max   count
Age Group                                        ...
>20        11029.00  12840.0   397.0  19.793451  ...  0.5470  1.025   397.0
20-30       9788.25  12842.0  9616.0  25.453827  ...  0.5640  1.500  9616.0
30-40       8766.00  12843.0  2813.0  33.414504  ...  0.5620  1.064  2813.0
40-50      10884.25  12390.0    18.0  41.833333  ...  0.5875  1.000    18.0
<50             NaN      NaN     0.0        NaN  ...     NaN    NaN     0.0


               mean       std  min    25%    50%    75%    max
Age Group
>20        0.116806  0.084915  0.0  0.059  0.094  0.153  0.667
20-30      0.129570  0.093166  0.0  0.065  0.101  0.176  1.000
30-40      0.141032  0.097900  0.0  0.070  0.112  0.192  1.000
40-50      0.064889  0.101516  0.0  0.003  0.049  0.080  0.445
<50             NaN       NaN  NaN    NaN    NaN    NaN    NaN

[5 rows x 112 columns]